[package]
authors = ["equal-l2 <eng.equall2@gmail.com>"]
name = "server"
version = "0.1.0"

[dependencies]
lazy_static = "1.0"
rocket = { version = "0.3.12", features = ["tls"] }
rocket-simpleauth = "0.4"
rocket_codegen = "0.3.12"
serde = "1.0.66"
serde_derive = "1.0.66"
toml = "0.4.6"
chan = "0.1"
chan-signal = "0.3"
rust-crypto = "0.2.36"

[dependencies.rppal]
optional = true
version = "0.7.0"

[features]
default = ["gpio"]
gpio = ["rppal"]
